### ISSUE TITLE
delete function actually working, but getting a 500 error from the wrapper

### ISSUE THREAD

**Issue by himleyb85** [himleyb85/bitR#123]
`AttributeError at /bmapi/deletemessage
'str' object has no attribute 'items'

Request Method: POST
Request URL: http://127.0.0.1:8000/bmapi/deletemessage
Django Version: 1.7.4
Python Executable: /home/computeruser/byteacademy/bitR/venv/bin/python3
Python Version: 3.4.0
Python Path: ['/home/computeruser/byteacademy/bitR', '/home/computeruser/byteacademy/bitR/venv/lib/python3.4', '/home/computeruser/byteacademy/bitR/venv/lib/python3.4/plat-x86_64-linux-gnu', '/home/computeruser/byteacademy/bitR/venv/lib/python3.4/lib-dynload', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-x86_64-linux-gnu', '/home/computeruser/byteacademy/bitR/venv/lib/python3.4/site-packages']
Server time: Thu, 5 Feb 2015 22:31:13 +0000
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'bitweb',
 'bmapi',
 'django_forms_bootstrap')
Installed Middleware:
('django.middleware.cache.UpdateCacheMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.cache.FetchFromCacheMiddleware',
 'bitR.middleware.tokenAuth')

Traceback:
File "/home/computeruser/byteacademy/bitR/venv/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/computeruser/byteacademy/bitR/venv/lib/python3.4/site-packages/django/views/generic/base.py" in view
  69.             return self.dispatch(request, *args, **kwargs)
File "/home/computeruser/byteacademy/bitR/venv/lib/python3.4/site-packages/django/views/generic/base.py" in dispatch
  87.         return handler(request, *args, **kwargs)
File "/home/computeruser/byteacademy/bitR/bmapi/views.py" in post
  135.         print(   BMclient.call( 'trashMessage',  request.json['msgid'] ) )
File "/home/computeruser/byteacademy/bitR/bmapi/wrapper.py" in call
  41. 		return self.clean(response)
File "/home/computeruser/byteacademy/bitR/bmapi/wrapper.py" in clean
  46. 			for key,value in dic.items():`

**Comment by himleyb85** [comment]
When I click on delete, I get this error in the javascript console, and an alert in the browser ('server failed'), even though the client actually deletes it.  However, if I encode the message ID when I give it to the wrapper like this:

`BMclient.call( 'trashMessage',  BMclient._encode(request.json['msgid']) )`

It doesn't give me an error in the console or give me an alert (although it does give a status 500 if i print the response)

**Comment by himleyb85** [comment]
temporary fix, still needs to be addressed:
https://github.com/himleyb85/bitR/blob/master/bmapi/views.py#L135

**Comment by wmantly** [comment]
Ok, i see the issue in the BM API and will fix. The messages id should not be encoded, as it not decoded.

**Comment by wmantly** [comment]
Fixed in https://github.com/wmantly/PyBitmessage/pull/8

Please be aware that the BM API has a different API call for deleting inbox messages then for sent messages.

And please assign me any issues regarding the BM API.

**Comment by himleyb85** [comment]
Updated pybitmessage, and am testing by removing the try catch temporary fix.  Now getting this error:

CannotSendRequest at /bmapi/deletemessage
Request-sent

Request Method: POST
Request URL: http://127.0.0.1:8000/bmapi/deletemessage
Django Version: 1.7.4
Python Executable: /home/computeruser/byteacademy/bitR/venv/bin/python3
Python Version: 3.4.0
Python Path: ['/home/computeruser/byteacademy/bitR', '/home/computeruser/byteacademy/bitR/venv/lib/python3.4', '/home/computeruser/byteacademy/bitR/venv/lib/python3.4/plat-x86_64-linux-gnu', '/home/computeruser/byteacademy/bitR/venv/lib/python3.4/lib-dynload', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-x86_64-linux-gnu', '/home/computeruser/byteacademy/bitR/venv/lib/python3.4/site-packages']
Server time: Fri, 6 Feb 2015 15:15:38 +0000
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'bitweb',
 'bmapi',
 'django_forms_bootstrap')
Installed Middleware:
('django.middleware.cache.UpdateCacheMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.cache.FetchFromCacheMiddleware',
 'bitR.middleware.tokenAuth')

Traceback:
File "/home/computeruser/byteacademy/bitR/venv/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/computeruser/byteacademy/bitR/venv/lib/python3.4/site-packages/django/views/generic/base.py" in view
  69.             return self.dispatch(request, *args, **kwargs)
File "/home/computeruser/byteacademy/bitR/venv/lib/python3.4/site-packages/django/views/generic/base.py" in dispatch
  87.         return handler(request, *args, **kwargs)
File "/home/computeruser/byteacademy/bitR/bmapi/views.py" in post
  134.         BMclient.call( 'trashMessage',  request.json['msgid']  )
File "/home/computeruser/byteacademy/bitR/bmapi/wrapper.py" in call
  37. 		response = eval( call, { 'self': self } )
File "/usr/lib/python3.4/xmlrpc/client.py" in __call__
  1089.         return self.__send(self.__name, args)
File "/usr/lib/python3.4/xmlrpc/client.py" in __request
  1419.             verbose=self.__verbose
File "/usr/lib/python3.4/xmlrpc/client.py" in request
  1131.                 return self.single_request(host, handler, request_body, verbose)
File "/usr/lib/python3.4/xmlrpc/client.py" in single_request
  1143.             http_conn = self.send_request(host, handler, request_body, verbose)
File "/usr/lib/python3.4/xmlrpc/client.py" in send_request
  1248.             connection.putrequest("POST", handler, skip_accept_encoding=True)
File "/usr/lib/python3.4/http/client.py" in putrequest
  948.             raise CannotSendRequest(self.__state)
