### ISSUE TITLE
Clicking sent mail produces server error

### ISSUE THREAD

**Issue by bgilroy26** [himleyb85/bitR#220]
[When Sent Mail Button Pressed](https://cloud.githubusercontent.com/assets/1566305/6197184/4d7b48e6-b3af-11e4-831f-7ddaad2bc1f9.png)

**Comment by wmantly** [comment]
This may have been fixed in pull #222, please test.

**Comment by bgilroy26** [comment]
All better!

[Step 1](https://cloud.githubusercontent.com/assets/1566305/6259417/57492f60-b7a0-11e4-95d8-d07d1394c654.png)


[Step 2](https://cloud.githubusercontent.com/assets/1566305/6259408/461e20a6-b7a0-11e4-9b8f-2986fe95d7e2.png)

[Step 3](https://cloud.githubusercontent.com/assets/1566305/6259406/437f0f86-b7a0-11e4-94ff-0668b690cafb.png)

**Comment by wmantly** [comment]
Thank you!!
