### ISSUE TITLE
creating new identity doesn't automatically add to compose modal "sent from" list

### ISSUE THREAD

**Issue by himleyb85** [himleyb85/bitR#223]

**Comment by bgilroy26** [comment]
[Error message when there aren't any identities on the "From" list and you try to send a message](https://cloud.githubusercontent.com/assets/1566305/6257816/48566ba8-b791-11e4-95f1-90cedfc4a0e8.png)

**Comment by wmantly** [comment]
This will be fixed when the client side DB handles the identities. A current work around is to refresh the page.

**Comment by bgilroy26** [comment]
All better!

[Step 1](https://cloud.githubusercontent.com/assets/1566305/6259417/57492f60-b7a0-11e4-95d8-d07d1394c654.png)


[Step 2](https://cloud.githubusercontent.com/assets/1566305/6259408/461e20a6-b7a0-11e4-9b8f-2986fe95d7e2.png)

[Step 3](https://cloud.githubusercontent.com/assets/1566305/6259406/437f0f86-b7a0-11e4-94ff-0668b690cafb.png)

**Comment by wmantly** [comment]
No, if you create a new identity the page must be refreshed to see it the "from" list. So this issues is still un-resolved.

The "from" list should be populated when the send modal opened, or when there is a change to the list of a available senders. Currently its only populated when the page is ready.
