### ISSUE TITLE
should be a regular check that goes over all the tokens in the db and deletes expired ones

### ISSUE THREAD

**Issue by himleyb85** [himleyb85/bitR#31]
erases all the tokens that are expired (i.e., if the user doesn't log out but a day goes by)
right now we have a created_at for date, so we check by adding timedelta of 1 day

so the database doesn't get cluttered up with a bunch of tokens of people who never log out

**Comment by wmantly** [comment]
At this point, keys are never deleted.
The check in the middleware file should delete keys when they are expired, this is a good start.
Also user should be able to see what keys have, when they expire and be able to delete them.
A scheduled job should clean the keys ever hour or so, look into this [django plugin](http://django-cron.readthedocs.org/en/latest/)

**Comment by adolfo0620** [comment]
wrote a trigger to clear old token form db the how to is in the readme
