### ISSUE TITLE
create chan modal shows up on inbox load

### ISSUE THREAD

**Issue by himleyb85** [himleyb85/bitR#45]
i've added the line
`    $( '#create_chan' ).modal('hide')`  
to inbox.js but it still pops up for a second

**Comment by wmantly** [comment]
IIf you want something to start hidden, add style="display:none" to the HTML element.

**Comment by himleyb85** [comment]
that didn't work

**Comment by wmantly** [comment]
let me see the HTML

**Comment by himleyb85** [comment]
`	<div class="modal fade" id="create_chan" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="display:none">
	  <div class="modal-dialog modal-sm">
		<div class="modal-content">
	        <div class="modal-header">
	 			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
	        	<h4 class="modal-title" id="myModalLabel">New Chan</h4>
	        </div>
		    <div class="modal-body">
				<form>
				  <div class="form-group">
				    <label for="Chan Name">Chan Nickname</label>
				    <input type="email" class="form-control" id="Chan Name" placeholder="Enter Chan Name">
				    <p class="help-block">Enter a name for your chan. If you choose a sufficiently complex chan name (like a strong and unique passphrase) and none of your friends share it publicly then the chan will be secure and private. If you and someone else both create a chan with the same chan name then it is currently very likely that they will be the same chan!</p>
		            <button type="button" class="btn" data-dismiss="modal">Cancel</button>
			        <button type="button" id="create_chan_button" class="btn btn-material-blue-grey-500" data-dismiss="modal">Create</button>
				  </div>
				</form>
		    </div>
	    </div>
	  </div>
	</div>`

**Comment by wmantly** [comment]
http://jsfiddle.net/2p2v4/208/
It should work!

**Comment by himleyb85** [comment]
checked firefox, chrome, and chromium on ubuntu 14 doesn't work for me

**Comment by wmantly** [comment]
that fiddle doesnt work for you?

**Comment by himleyb85** [comment]
oh, the fiddle code works

**Comment by wmantly** [comment]
Fixed in #52
