### ISSUE TITLE
function from line 23-37 in bitweb/static/js/inbox.js doesn't fully work

### ISSUE THREAD

**Issue by himleyb85** [himleyb85/bitR#51]
The function works as long as there are identities returned (it correctly adds the identities to the dropdown), but i also want it to automatically show the modal if there are none returned, which it doesn't do

**Comment by wmantly** [comment]
Please dont use just line number;
Add a code snippet or add a [permanent link to the file](https://help.github.com/articles/getting-permanent-links-to-files/#press-y-to-permalink-to-a-file-in-a-specific-commit)

Also add the complete path to the file.
