### ISSUE TITLE
create address book

### ISSUE THREAD

**Issue by himleyb85** [himleyb85/bitR#84]
so you can give names to addresses so when they show up in your inbox you don't just see " from  BM-2cURdGXeZRcczTVcsLrhDMXg2N8yRFf1ZX "

**Comment by wmantly** [comment]
Address book is mostly done. Need button to edit and delete on the GUI. Back end code is there for delete, but not editing.

Adding auto complete on "to" fields.

**Comment by wmantly** [comment]
Done, in #211
